migrate(
  (app) => {
    const col = app.findCollectionByNameOrId('cid10_codes')
    const data = [
      ['A09', 'Diarréia e gastroenterite de origem infecciosa presumível'],
      ['B00', 'Infecções pelo vírus do herpes'],
      ['B02', 'Herpes zoster'],
      ['B05', 'Sarampo'],
      ['B06', 'Rubéola'],
      ['B19', 'Doença pelo vírus da hepatite não especificada'],
      ['C16', 'Neoplasia maligna do estômago'],
      ['C18', 'Neoplasia maligna do cólon'],
      ['C20', 'Neoplasia maligna do reto'],
      ['C22', 'Neoplasia maligna do fígado e vias biliares intra-hepáticas'],
      ['C25', 'Neoplasia maligna do pâncreas'],
      ['C34', 'Neoplasia maligna dos brônquios e do pulmão'],
      ['C50', 'Neoplasia maligna da mama'],
      ['C53', 'Neoplasia maligna do colo do útero'],
      ['C61', 'Neoplasia maligna da próstata'],
      ['C67', 'Neoplasia maligna da bexiga'],
      ['D50', 'Anemia por deficiência de ferro'],
      ['D51', 'Anemia por deficiência de vitamina B12'],
      ['D64', 'Outras anemias'],
      ['E03', 'Outros hipotireoidismos'],
      ['E05', 'Tireotoxicose [hipertireoidismo]'],
      ['E10', 'Diabetes mellitus insulino-dependente'],
      ['E11', 'Diabetes mellitus não-insulino-dependente'],
      ['E14', 'Diabetes mellitus não especificado'],
      ['E46', 'Desnutrição protéico-calórica não especificada'],
      ['E55', 'Deficiência de vitamina D'],
      ['E66', 'Obesidade'],
      ['E78', 'Distúrbios do metabolismo das lipoproteínas e outras lipidemias'],
      ['F10', 'Transtornos mentais e de comportamento devidos ao uso de álcool'],
      ['F17', 'Transtornos mentais e de comportamento devidos ao uso de tabaco'],
      ['F20', 'Esquizofrenia'],
      ['F31', 'Transtorno afetivo bipolar'],
      ['F32', 'Episódio depressivo'],
      ['F33', 'Transtorno depressivo recorrente'],
      ['F40', 'Fobias'],
      ['F41', 'Outros transtornos ansiosos'],
      ['F43', 'Reação a estresse grave e transtornos de adaptação'],
      ['F45', 'Transtornos somatomorfos'],
      ['F50', 'Transtornos da alimentação'],
      ['F90', 'Transtornos de hipercinesia [TDAH]'],
      ['G40', 'Epilepsia'],
      ['G43', 'Enxaqueca'],
      ['G44', 'Outras síndromes de cefaleia'],
      ['G45', 'Síndromes cerebrovasculares transitórias'],
      ['G47', 'Transtornos do sono'],
      ['H10', 'Conjuntivite'],
      ['H25', 'Catarata senil'],
      ['H40', 'Glaucoma'],
      ['H52', 'Transtornos de refração e acomodação'],
      ['H65', 'Otite média não supurativa'],
      ['H66', 'Otite média supurativa'],
      ['I10', 'Hipertensão essencial (primária)'],
      ['I11', 'Cardiopatia hipertensiva'],
      ['I20', 'Angina pectoris'],
      ['I21', 'Infarto agudo do miocárdio'],
      ['I25', 'Doença isquêmica crônica do coração'],
      ['I48', 'Fibrilação e flutter atriais'],
      ['I50', 'Insuficiência cardíaca'],
      ['I63', 'Infarto cerebral'],
      ['I64', 'Acidente vascular cerebral não especificado'],
      ['I69', 'Seqüelas de doenças cerebrovasculares'],
      ['I70', 'Aterosclerose'],
      ['I80', 'Flebite e tromboflebite'],
      ['I83', 'Varizes dos membros inferiores'],
      ['J00', 'Nasofaringite aguda (resfriado comum)'],
      ['J01', 'Sinusite aguda'],
      ['J02', 'Faringite aguda'],
      ['J03', 'Amigdalite aguda'],
      ['J06', 'Infecções agudas das vias aéreas superiores'],
      ['J11', 'Influenza por vírus não identificado'],
      ['J13', 'Pneumonia por Streptococcus pneumoniae'],
      ['J18', 'Pneumonia por microrganismo não especificado'],
      ['J20', 'Bronquite aguda'],
      ['J21', 'Bronquiolite aguda'],
      ['J32', 'Sinusite crônica'],
      ['J35', 'Doenças crônicas das amígdalas e adenoides'],
      ['J44', 'Outras doenças pulmonares obstrutivas crônicas [DPOC]'],
      ['J45', 'Asma'],
      ['J46', 'Estado asmático'],
      ['J90', 'Derrame pleural'],
      ['J96', 'Insuficiência respiratória'],
      ['K21', 'Doença de refluxo gastroesofágico'],
      ['K25', 'Úlcera gástrica'],
      ['K26', 'Úlcera duodenal'],
      ['K29', 'Gastrite e duodenite'],
      ['K30', 'Dispepsia'],
      ['K35', 'Apendicite aguda'],
      ['K40', 'Hérnia inguinal'],
      ['K50', 'Doença de Crohn'],
      ['K51', 'Colite ulcerativa'],
      ['K58', 'Síndrome do intestino irritável'],
      ['K80', 'Colelitíase'],
      ['K81', 'Colecistite'],
      ['K85', 'Pancreatite aguda'],
      ['L01', 'Impetigo'],
      ['L03', 'Celulite'],
      ['L20', 'Dermatite atópica'],
      ['L21', 'Dermatite seborreica'],
      ['L30', 'Dermatite não especificada'],
      ['L40', 'Psoríase'],
      ['L50', 'Urticária'],
      ['L70', 'Acne'],
      ['L80', 'Vitiligo'],
      ['L89', 'Úlcera de pressão'],
    ]
    for (const [code, desc] of data) {
      try {
        app.findFirstRecordByData('cid10_codes', 'code', code)
      } catch (_) {
        const rec = new Record(col)
        rec.set('code', code)
        rec.set('description', desc)
        app.save(rec)
      }
    }
  },
  (app) => {},
)
