migrate(
  (app) => {
    const col = app.findCollectionByNameOrId('medications')
    const data = [
      {
        n: 'AAS 100mg',
        a: 'Ácido Acetilsalicílico',
        l: 'Bayer',
        p: 'Comprimidos',
        i: 'Prevenção cardiovascular, antiagregante plaquetário.',
        c: 'Úlcera péptica ativa, hemofilia, gravidez 3º trimestre.',
        t: 'Aumenta risco de sangramento com anticoagulantes e AINEs.',
      },
      {
        n: 'Atenolol 25mg',
        a: 'Atenolol',
        l: 'Medley',
        p: 'Comprimidos',
        i: 'Hipertensão, angina, arritmias cardíacas.',
        c: 'Bradicardia severa, asma, IC descompensada.',
        t: 'Potencializa bloqueadores de cálcio. Mascara hipoglicemia.',
      },
      {
        n: 'Atorvastatina 20mg',
        a: 'Atorvastatina',
        l: 'Pfizer',
        p: 'Comprimidos',
        i: 'Hipercolesterolemia, prevenção cardiovascular.',
        c: 'Doença hepática ativa, gravidez, lactação.',
        t: 'Risco de miopatia com macrolídeos e azólicos.',
      },
      {
        n: 'Azitromicina 500mg',
        a: 'Azitromicina',
        l: 'Eurofarma',
        p: 'Comprimidos',
        i: 'Infecções respiratórias, otite, sinusite, faringite.',
        c: 'Alergia a macrolídeos, prolongamento QT.',
        t: 'Antagoniza penicilinas. Cuidado com anticoagulantes.',
      },
      {
        n: 'Captopril 25mg',
        a: 'Captopril',
        l: 'Medley',
        p: 'Comprimidos',
        i: 'Hipertensão, IC, nefropatia diabética.',
        c: 'Gravidez, estenose bilateral de artéria renal.',
        t: 'Hipercalemia com diuréticos poupadores de potássio.',
      },
      {
        n: 'Cefalexina 500mg',
        a: 'Cefalexina',
        l: 'Teuto',
        p: 'Cápsulas',
        i: 'Infecções de pele, respiratórias, urinárias.',
        c: 'Alergia a cefalosporinas e penicilinas.',
        t: 'Sinérgico com aminoglicosídeos.',
      },
      {
        n: 'Cetoconazol 200mg',
        a: 'Cetoconazol',
        l: 'Janssen',
        p: 'Comprimidos',
        i: 'Micoses sistêmicas, candidíase, dermatofitoses.',
        c: 'Insuficiência hepática, gravidez, uso com estatinas.',
        t: 'Inibe CYP3A4. Contraindicado com estatinas.',
      },
      {
        n: 'Citalopram 20mg',
        a: 'Cloridrato de Citalopram',
        l: 'Eurofarma',
        p: 'Comprimidos',
        i: 'Depressão, transtorno do pânico, ansiedade.',
        c: 'Uso com IMAO, síndrome QT longo.',
        t: 'Síndrome serotoninérgica com triptanos e tramadol.',
      },
      {
        n: 'Clonazepam 2mg',
        a: 'Clonazepam',
        l: 'Cristália',
        p: 'Comprimidos',
        i: 'Ansiedade, epilepsia, transtorno do pânico.',
        c: 'Miastenia gravis, insuficiência respiratória severa.',
        t: 'Potencializa opioides e álcool.',
      },
      {
        n: 'Cloridrato de Sertralina 50mg',
        a: 'Cloridrato de Sertralina',
        l: 'Pfizer',
        p: 'Comprimidos',
        i: 'Depressão, TOC, pânico, TEPT.',
        c: 'Uso com IMAO, hepatopatia grave.',
        t: 'Síndrome serotoninérgica com outros SSRIs.',
      },
      {
        n: 'Diazepam 5mg',
        a: 'Diazepam',
        l: 'EMS',
        p: 'Comprimidos',
        i: 'Ansiedade, espasmos musculares, abstinência alcoólica.',
        c: 'Miastenia gravis, insuficiência respiratória, apneia.',
        t: 'Potencializa álcool e opioides.',
      },
      {
        n: 'Doxiciclina 100mg',
        a: 'Cloridrato de Doxiciclina',
        l: 'EMS',
        p: 'Cápsulas',
        i: 'Acne, infecções respiratórias, DST, riquetsioses.',
        c: 'Gravidez, lactação, menores de 8 anos.',
        t: 'Reduz absorção com antiácidos e cálcio.',
      },
      {
        n: 'Escitalopram 10mg',
        a: 'Oxalato de Escitalopram',
        l: 'Medley',
        p: 'Comprimidos',
        i: 'Depressão, ansiedade generalizada, pânico.',
        c: 'Uso com IMAO, síndrome QT longo.',
        t: 'Síndrome serotoninérgica com tramadol.',
      },
      {
        n: 'Espironolactona 25mg',
        a: 'Espironolactona',
        l: 'Germed',
        p: 'Comprimidos',
        i: 'IC, hipertensão, hiperaldosteronismo, ascite.',
        c: 'Hipercalemia, IR aguda, anúria.',
        t: 'Hipercalemia com IECA. Cuidado com digoxina.',
      },
      {
        n: 'Fluoxetina 20mg',
        a: 'Cloridrato de Fluoxetina',
        l: 'EMS',
        p: 'Cápsulas',
        i: 'Depressão, bulimia, TOC, TDPM.',
        c: 'Uso com IMAO, hepatopatia.',
        t: 'Inibe CYP2D6. Aumenta nível de TCA e varfarina.',
      },
      {
        n: 'Furosemida 40mg',
        a: 'Furosemida',
        l: 'EMS',
        p: 'Comprimidos',
        i: 'Edema, IC, hipertensão, hipercalemia.',
        c: 'Anúria, hipovolemia, hipersensibilidade a sulfonamidas.',
        t: 'Ototoxicidade com aminoglicosídeos. Hipocalemia.',
      },
      {
        n: 'Hidroclorotiazida 25mg',
        a: 'Hidroclorotiazida',
        l: 'EMS',
        p: 'Comprimidos',
        i: 'Hipertensão, IC, edema, diabetes insipidus.',
        c: 'Anúria, IR severa, hipersensibilidade a sulfonamidas.',
        t: 'Hipocalemia com corticoides. Reduz efeito de antidiabéticos.',
      },
      {
        n: 'Levotiroxina 25mcg',
        a: 'Levotiroxina Sódica',
        l: 'Pfizer',
        p: 'Comprimidos',
        i: 'Hipotireoidismo, bócio, supressão de TSH.',
        c: 'Tireotoxicose, IAM recente.',
        t: 'Reduz absorção com cálcio e ferro. Aumenta efeito de anticoagulantes.',
      },
      {
        n: 'Loratadina 10mg',
        a: 'Loratadina',
        l: 'Medley',
        p: 'Comprimidos',
        i: 'Rinite alérgica, urticária, alergias cutâneas.',
        c: 'Hipersensibilidade, hepatopatia severa.',
        t: 'Aumenta nível com cetoconazol e eritromicina.',
      },
      {
        n: 'Maleato de Enalapril 10mg',
        a: 'Maleato de Enalapril',
        l: 'Teuto',
        p: 'Comprimidos',
        i: 'Hipertensão, IC, nefropatia.',
        c: 'Gravidez, estenose bilateral de artéria renal.',
        t: 'Hipercalemia com diuréticos poupadores.',
      },
      {
        n: 'Naproxeno 500mg',
        a: 'Naproxeno',
        l: 'Medley',
        p: 'Comprimidos',
        i: 'Dor, inflamação, artrite, dismenorreia.',
        c: 'Úlcera péptica ativa, IR, gravidez 3º trimestre.',
        t: 'Aumenta sangramento com anticoagulantes.',
      },
      {
        n: 'Nimesulida 100mg',
        a: 'Nimesulida',
        l: 'EMS',
        p: 'Comprimidos',
        i: 'Dor aguda, osteoartrite, dismenorreia.',
        c: 'Úlcera péptica, hepatopatia, gravidez, IR.',
        t: 'Toxicidade hepática com paracetamol.',
      },
      {
        n: 'Prednisona 20mg',
        a: 'Prednisona',
        l: 'EMS',
        p: 'Comprimidos',
        i: 'Doenças inflamatórias, autoimunes, alergias, asma.',
        c: 'Infecções sistêmicas não tratadas.',
        t: 'Reduz efeito de antidiabéticos. Aumenta toxicidade de AINEs.',
      },
      {
        n: 'Propranolol 40mg',
        a: 'Cloridrato de Propranolol',
        l: 'Aché',
        p: 'Comprimidos',
        i: 'Hipertensão, enxaqueca, ansiedade, tremor essencial.',
        c: 'Asma, bradicardia, IC descompensada.',
        t: 'Potencializa bloqueadores de cálcio. Mascara hipoglicemia.',
      },
      {
        n: 'Risperidona 1mg',
        a: 'Risperidona',
        l: 'Janssen',
        p: 'Comprimidos',
        i: 'Esquizofrenia, transtorno bipolar, irritabilidade em autismo.',
        c: 'Demência com corpos de Lewy, hipersensibilidade.',
        t: 'Potencializa sedativos. Hipotensão com anti-hipertensivos.',
      },
      {
        n: 'Rosuvastatina 20mg',
        a: 'Rosuvastatina',
        l: 'AstraZeneca',
        p: 'Comprimidos',
        i: 'Hipercolesterolemia, prevenção cardiovascular.',
        c: 'Doença hepática ativa, gravidez, lactação.',
        t: 'Risco de miopatia com ciclosporina.',
      },
      {
        n: 'Sinvastatina 20mg',
        a: 'Sinvastatina',
        l: 'Medley',
        p: 'Comprimidos',
        i: 'Hipercolesterolemia, prevenção cardiovascular.',
        c: 'Doença hepática ativa, gravidez, uso com itraconazol.',
        t: 'Miopatia com macrolídeos e azólicos. Cuidado com amiodarona.',
      },
      {
        n: 'Sulfato de Salbutamol 4mg',
        a: 'Sulfato de Salbutamol',
        l: 'EMS',
        p: 'Comprimidos',
        i: 'Asma, DPOC, bronquite, broncoespasmo.',
        c: 'Hipersensibilidade, taquiarritmia severa.',
        t: 'Hipocalemia com diuréticos. Potencializa estimulantes.',
      },
      {
        n: 'Valproato de Sódio 500mg',
        a: 'Valproato de Sódio',
        l: 'Abbott',
        p: 'Comprimidos',
        i: 'Epilepsia, transtorno bipolar, prevenção de enxaqueca.',
        c: 'Gravidez, hepatopatia, deficiência de ureia.',
        t: 'Aumenta toxicidade com lamotrigina. Cuidado com aspirina.',
      },
      {
        n: 'Varfarina 5mg',
        a: 'Varfarina',
        l: 'Cristália',
        p: 'Comprimidos',
        i: 'TVP, TEP, fibrilação atrial, próteses valvares.',
        c: 'Gravidez, sangramento ativo, úlcera péptica.',
        t: 'Inúmeras. Aumenta com AAS, AINEs, macrolídeos. Reduz com vitamina K.',
      },
      {
        n: 'Zolpidem 10mg',
        a: 'Tartarato de Zolpidem',
        l: 'EMS',
        p: 'Comprimidos',
        i: 'Insônia de curto prazo.',
        c: 'Miastenia gravis, insuficiência respiratória, apneia do sono.',
        t: 'Depressão do SNC com álcool e opioides.',
      },
      {
        n: 'Cloridrato de Metoclopramida 10mg',
        a: 'Cloridrato de Metoclopramida',
        l: 'EMS',
        p: 'Comprimidos',
        i: 'Náuseas, vômitos, refluxo gastresofágico.',
        c: 'Obstrução intestinal, feocromocitoma, discinesia tardia.',
        t: 'Extrapiramidal com antipsicóticos. Reduz absorção de levodopa.',
      },
      {
        n: 'Sulfametoxazol + Trimetoprima 400mg+80mg',
        a: 'Sulfametoxazol + Trimetoprima',
        l: 'EMS',
        p: 'Comprimidos',
        i: 'ITU, infecções respiratórias, pielonefrite, Pneumocystis.',
        c: 'Gravidez 1º trimestre, IR severa, alergia a sulfas.',
        t: 'Aumenta efeito de varfarina. Potencializa toxicidade do metotrexato.',
      },
      {
        n: 'Ciprofloxacino 500mg',
        a: 'Cloridrato de Ciprofloxacino',
        l: 'EMS',
        p: 'Comprimidos',
        i: 'ITU, infecções respiratórias, gastroenterite, pele.',
        c: 'Gravidez, lactação, crianças, tendinite prévia.',
        t: 'Reduz absorção com cálcio e ferro. Aumenta varfarina.',
      },
    ]
    for (const m of data) {
      try {
        app.findFirstRecordByData('medications', 'name', m.n)
      } catch (_) {
        const rec = new Record(col)
        rec.set('name', m.n)
        rec.set('active_ingredient', m.a)
        rec.set('laboratory', m.l)
        rec.set('presentation', m.p)
        rec.set('indications', m.i)
        rec.set('contraindications', m.c)
        rec.set('interactions', m.t)
        app.save(rec)
      }
    }
  },
  (app) => {},
)
